# Generated by Django 6.0.2 on 2026-02-14 22:20

import django.db.models.deletion
import django.utils.timezone
import sales.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_shippingcompany_payment_methods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('SENT', 'Enviado'), ('APPROVED', 'Aprovado'), ('CONVERTED', 'Convertido em Pedido'), ('CANCELED', 'Cancelado')], default='DRAFT', max_length=12)),
                ('quote_date', models.DateField(default=django.utils.timezone.localdate)),
                ('delivery_deadline', models.DateField(blank=True, help_text='Prazo de entrega previsto', null=True)),
                ('freight_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('freight_responsible', models.CharField(choices=[('STORE', 'Loja'), ('CUSTOMER', 'Cliente'), ('CARRIER', 'Transportadora')], default='CUSTOMER', help_text='Quem paga o frete', max_length=10)),
                ('shipping_payment_method', models.CharField(blank=True, help_text='Método de pagamento selecionado da transportadora', max_length=200)),
                ('discount_percent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6, validators=[sales.models.validate_discount_percent])),
                ('discount_authorized_at', models.DateTimeField(blank=True, null=True)),
                ('payment_description', models.CharField(blank=True, max_length=200)),
                ('total_value_snapshot', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='core.customer')),
                ('discount_authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_quote_discounts', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to=settings.AUTH_USER_MODEL)),
                ('shipping_company', models.ForeignKey(blank=True, help_text='Transportadora responsável (se aplicável)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='core.shippingcompany')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('is_total_conference', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('SENT', 'Enviado'), ('DONE', 'Concluído'), ('CANCELED', 'Cancelado')], default='OPEN', max_length=10)),
                ('purchase_condition_text', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.supplier')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('condition_text', models.CharField(blank=True, max_length=200)),
                ('architect_percent', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quote')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_items', to='core.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('purchase_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order')),
                ('quote_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='sales.quoteitem')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=sales.models.quote_item_tmp_path)),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sales.quoteitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['number'], name='sales_quote_number_c8c661_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['quote_date'], name='sales_quote_quote_d_56572e_idx'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['status'], name='sales_quote_status_77c7d0_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['number'], name='sales_order_number_c248af_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['quote'], name='sales_order_quote_i_ef25ed_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['supplier'], name='sales_order_supplie_0917d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('is_total_conference', True)), fields=('quote',), name='uniq_total_order_per_quote'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('is_total_conference', True), ('supplier__isnull', False), _negated=True), name='total_order_has_no_supplier'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['quote'], name='sales_quote_quote_i_cc7d01_idx'),
        ),
        migrations.AddIndex(
            model_name='quoteitem',
            index=models.Index(fields=['supplier'], name='sales_quote_supplie_449438_idx'),
        ),
    ]
