# Generated by Django 6.0.2 on 2026-02-15 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='payment_fee_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Taxa aplicada conforme parcelas', max_digits=6),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_installments',
            field=models.PositiveIntegerField(default=1, help_text='Número de parcelas (1 = à vista)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_type',
            field=models.CharField(blank=True, help_text='Tipo de pagamento (dinheiro, pix, cartão, etc.)', max_length=20),
        ),
    ]
