# Generated by Django 6.0.2 on 2026-02-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_quote_payment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='payment_description',
        ),
    ]
