# Generated by Django 6.0.2 on 2026-02-15 14:49

import sales.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_quote_payment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='discount_percent',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[sales.models.validate_discount_percent]),
        ),
        migrations.AlterField(
            model_name='quote',
            name='payment_fee_percent',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Taxa aplicada conforme parcelas', max_digits=5),
        ),
    ]
