# Generated by Django 6.0.2 on 2026-02-15 14:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_quote_discount_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='has_architect',
            field=models.BooleanField(default=False, help_text='Cliente possui arquiteto?'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='architect_percent',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4),
        ),
    ]
