# Generated by Django 6.0.2 on 2026-02-15 14:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_quote_has_architect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='architect_percent',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=4, null=True),
        ),
    ]
