# Generated by Django 6.0.2 on 2026-03-03 01:42

import sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_quoteitem_architect_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoteitemimage',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='quoteitemimage',
            name='image',
            field=models.ImageField(upload_to=sales.models.quote_item_image_path),
        ),
    ]
