# Generated by Django 6.0.2 on 2026-03-15 20:30

import django.db.models.deletion
import django.utils.timezone
import sales.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cpf_cnpj_required_constraint'),
        ('sales', '0008_proposalconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Pedido de Compra', 'verbose_name_plural': 'Pedidos de Compra'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name': 'Orçamento', 'verbose_name_plural': 'Orçamentos'},
        ),
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'verbose_name': 'Item do Orçamento', 'verbose_name_plural': 'Itens do Orçamento'},
        ),
        migrations.AlterModelOptions(
            name='quoteitemimage',
            options={'verbose_name': 'Imagem do Item', 'verbose_name_plural': 'Imagens do Item'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_total_conference',
            field=models.BooleanField(default=False, verbose_name='Conferência Total'),
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_condition_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Condição de Compra'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.quote', verbose_name='Orçamento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('SENT', 'Enviado'), ('DONE', 'Concluído'), ('CANCELED', 'Cancelado')], default='OPEN', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.supplier', verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.order', verbose_name='Pedido'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=160, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='purchase_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Custo de Compra'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Qtd'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='core.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='delivery_deadline',
            field=models.DateField(blank=True, help_text='Prazo de entrega previsto', null=True, verbose_name='Prazo de Entrega'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='discount_authorized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Desconto Autorizado em'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='discount_authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorized_quote_discounts', to=settings.AUTH_USER_MODEL, verbose_name='Desconto Autorizado por'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='discount_percent',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5, validators=[sales.models.validate_discount_percent], verbose_name='Desconto (%)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='freight_responsible',
            field=models.CharField(choices=[('STORE', 'Loja'), ('CUSTOMER', 'Cliente'), ('CARRIER', 'Transportadora')], default='CUSTOMER', help_text='Quem paga o frete', max_length=10, verbose_name='Responsável pelo Frete'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='freight_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor do Frete'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='has_architect',
            field=models.BooleanField(default=False, help_text='Cliente possui arquiteto?', verbose_name='Possui Arquiteto'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='number',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='payment_fee_percent',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='Taxa aplicada conforme parcelas', max_digits=5, verbose_name='Taxa de Pagamento (%)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='payment_installments',
            field=models.PositiveIntegerField(default=1, help_text='Número de parcelas (1 = à vista)', verbose_name='Parcelas'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='payment_type',
            field=models.CharField(blank=True, help_text='Tipo de pagamento (dinheiro, pix, cartão, etc.)', max_length=20, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote_date',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping_company',
            field=models.ForeignKey(blank=True, help_text='Transportadora responsável (se aplicável)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='core.shippingcompany', verbose_name='Transportadora'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='shipping_payment_method',
            field=models.CharField(blank=True, help_text='Método de pagamento selecionado da transportadora', max_length=200, verbose_name='Forma de Pagamento (Frete)'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('SENT', 'Enviado'), ('APPROVED', 'Aprovado'), ('CONVERTED', 'Convertido em Pedido'), ('CANCELED', 'Cancelado')], default='DRAFT', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='total_value_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total (R$)'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='architect_percent',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=4, null=True, verbose_name='Comissão Arq. (%)'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='condition_text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Condição'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='product_name',
            field=models.CharField(max_length=160, verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Qtd'),
        ),
        migrations.AlterField(
            model_name='quoteitem',
            name='unit_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Valor Unit.'),
        ),
    ]
