# Generated by Django 6.0.2 on 2026-03-15 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_remove_cpf_cnpj_required_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='delivery_deadline',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_deadline',
            field=models.DateField(blank=True, help_text='Data real de entrega acordada com o cliente', null=True, verbose_name='Prazo de Entrega (data real)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='delivery_weeks',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 semana'), (2, '2 semanas'), (3, '3 semanas'), (4, '4 semanas'), (5, '5 semanas'), (6, '6 semanas'), (7, '7 semanas'), (8, '8 semanas'), (9, '9 semanas'), (10, '10 semanas'), (11, '11 semanas'), (12, '12 semanas')], help_text='Prazo estimado em semanas', null=True, verbose_name='Prazo de Entrega (semanas)'),
        ),
    ]
