# Generated by Django 6.0.2 on 2026-03-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_delivery_weeks_and_order_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='freight_responsible',
            field=models.CharField(choices=[('STORE', 'Frete Próprio - Empresa'), ('CARRIER', 'Transportadora'), ('CUSTOMER', 'Cliente')], default='CUSTOMER', help_text='Quem paga o frete', max_length=10, verbose_name='Responsável pelo Frete'),
        ),
    ]
