# Generated by Django 6.0.3 on 2026-03-18 19:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_quote_freight_responsible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='payment_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Taxa (juros) aplicada conforme parcelas', max_digits=5, verbose_name='Taxa de Pagamento (%)'),
        ),
    ]
