# Generated by Django 6.0.2 on 2026-03-22 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_architect_alter_salesmarginconfig_total_margin'),
        ('sales', '0012_new_pricing_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='architect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotes', to='core.architect', verbose_name='Arquiteto'),
        ),
    ]
