# Generated by Django 6.0.2 on 2026-04-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_quote_split_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='delivery_weeks',
        ),
        migrations.AddField(
            model_name='quote',
            name='delivery_days_max',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Prazo máximo estimado em dias', null=True, verbose_name='Prazo Máximo de Entrega (dias)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='delivery_days_min',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Prazo mínimo estimado em dias', null=True, verbose_name='Prazo Mínimo de Entrega (dias)'),
        ),
    ]
