# Generated by Django 6.0.2 on 2026-05-07 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_delivery_days_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCommissionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_split', to='sales.quote', verbose_name='Orçamento')),
                ('users', models.ManyToManyField(blank=True, related_name='shared_commission_quotes', to=settings.AUTH_USER_MODEL, verbose_name='Vendedores')),
            ],
            options={
                'verbose_name': 'Divisão de Comissão',
                'verbose_name_plural': 'Divisões de Comissão',
            },
        ),
    ]
