# Generated by Django 6.0.2 on 2026-05-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_commission_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Aguardando Aprovação'), ('OPEN', 'Aberto'), ('SENT', 'Enviado'), ('ONGOING', 'Em Andamento'), ('DONE', 'Concluído'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Rascunho'), ('SENT', 'Enviado'), ('APPROVED', 'Aprovado'), ('CONVERTED', 'Convertido em Pedido'), ('POS_VENDA', 'Pós-Venda'), ('CANCELED', 'Cancelado')], default='DRAFT', max_length=12, verbose_name='Status'),
        ),
    ]
