# Generated by Django 6.0.2 on 2026-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transport_info',
            field=models.CharField(blank=True, max_length=300, verbose_name='Informações de Transporte'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Aguardando Aprovação'), ('ONGOING', 'Em Andamento'), ('DONE', 'Concluído'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=10, verbose_name='Status'),
        ),
    ]
