# Generated by Django 6.0.2 on 2026-07-03 16:43

import django.db.models.deletion
import sales.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_architect_pix_optional'),
        ('sales', '0020_quote_price_increase_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='quote',
            name='total_manual_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor somado (ou subtraído, se negativo) ao total após o arredondamento.', max_digits=12, verbose_name='Ajuste Manual (R$)'),
        ),
        migrations.AddField(
            model_name='quote',
            name='total_rounding_mode',
            field=models.CharField(choices=[('NONE', 'Sem arredondamento'), ('R1', 'Real (R$ 1)'), ('R10', 'Dezena (R$ 10)'), ('R50', 'R$ 50'), ('R100', 'Centena (R$ 100)')], default='NONE', help_text='Arredonda o total de venda ao cliente para um número redondo.', max_length=5, verbose_name='Arredondamento do Total'),
        ),
        migrations.CreateModel(
            name='SaleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('NF_COMPRA', 'NF de Compra'), ('NF_CLIENTE', 'NF do Cliente'), ('OUTRO', 'Outro')], default='OUTRO', max_length=12, verbose_name='Tipo')),
                ('file', models.FileField(upload_to=sales.models.sale_document_path, verbose_name='Arquivo')),
                ('description', models.CharField(blank=True, max_length=160, verbose_name='Descrição')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sales.quote', verbose_name='Venda')),
                ('supplier', models.ForeignKey(blank=True, help_text='Fornecedor da NF de compra (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_documents', to='core.supplier', verbose_name='Fornecedor')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sale_documents', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Documento da Venda',
                'verbose_name_plural': 'Documentos da Venda',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['quote'], name='sales_saled_quote_i_3e8123_idx'), models.Index(fields=['doc_type'], name='sales_saled_doc_typ_6f926a_idx')],
            },
        ),
    ]
