# Generated by Django 6.0.2 on 2026-07-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_alter_order_created_at'),
        ('sales', '0023_quote_sale_date'),
    ]

    operations = [
    ]
