# Generated by Django 6.0.2 on 2026-03-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='individual_target_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Meta Individual (R$)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SELLER', 'Vendedor'), ('ADMIN', 'Admin'), ('OWNER', 'Dono')], default='SELLER', max_length=10, verbose_name='Perfil'),
        ),
    ]
