# Generated by Django 6.0.3 on 2026-04-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_individual_target_value_alter_user_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SELLER', 'Vendedor'), ('STAFF', 'Equipe Interna'), ('ADMIN', 'Admin'), ('OWNER', 'Dono')], default='SELLER', max_length=10, verbose_name='Perfil'),
        ),
    ]
