# Generated by Django 6.0.2 on 2026-02-10 01:09

import core.validador
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da transportadora', max_length=120)),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ da transportadora (opcional)', max_length=18, validators=[core.validador.validate_cnpj])),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, help_text='Pessoa de contato na transportadora', max_length=100)),
                ('address', models.TextField(blank=True, help_text='Endereço completo')),
                ('notes', models.TextField(blank=True, help_text='Observações')),
                ('is_active', models.BooleanField(default=True, help_text='Transportadora ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transportadora',
                'verbose_name_plural': 'Transportadoras',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('supplier_number', models.CharField(help_text='Número/código do fornecedor', max_length=50, unique=True)),
                ('email', models.EmailField(help_text='E-mail único do fornecedor (identificador principal)', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Informações adicionais sobre o fornecedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('cpf', models.CharField(blank=True, help_text='CPF válido (com ou sem máscara)', max_length=14, validators=[core.validador.validate_cpf])),
                ('cnpj', models.CharField(blank=True, help_text='CNPJ válido (com ou sem máscara)', max_length=18, validators=[core.validador.validate_cnpj])),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('cpf', ''), _negated=True), fields=('cpf',), name='uniq_customer_cpf'), models.UniqueConstraint(condition=models.Q(('cnpj', ''), _negated=True), fields=('cnpj',), name='uniq_customer_cnpj'), models.CheckConstraint(condition=models.Q(('cpf', ''), ('cnpj', ''), _negated=True), name='cpf_or_cnpj_required')],
            },
        ),
        migrations.CreateModel(
            name='SupplierPaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text="Ex: '30/60/90 dias', 'À vista com 5% desconto', etc.", max_length=200)),
                ('days_to_pay', models.PositiveIntegerField(blank=True, help_text='Prazo em dias (opcional)', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Marcar como opção padrão para este fornecedor')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_options', to='core.supplier')),
            ],
            options={
                'ordering': ['-is_default', 'days_to_pay'],
            },
        ),
    ]
