# Generated by Django 6.0.2 on 2026-02-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingcompany',
            name='payment_methods',
            field=models.TextField(blank=True, help_text='Métodos de pagamento disponíveis (um por linha)'),
        ),
    ]
