# Generated by Django 6.0.2 on 2026-02-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shippingcompany_payment_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('CASH', 'Dinheiro'), ('PIX', 'PIX'), ('CREDIT_CARD', 'Cartão de Crédito'), ('CHEQUE', 'Cheque'), ('BOLETO', 'Boleto')], help_text='Tipo do método de pagamento', max_length=20)),
                ('installments', models.PositiveIntegerField(help_text='Número de parcelas (1 = à vista)')),
                ('fee_percent', models.DecimalField(decimal_places=3, default=0, help_text='Porcentagem de acréscimo (ex: 2.5 para 2.5%)', max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarifa de Pagamento',
                'verbose_name_plural': 'Tarifas de Pagamento',
                'ordering': ['payment_type', 'installments'],
                'unique_together': {('payment_type', 'installments')},
            },
        ),
    ]
