# Generated by Django 6.0.2 on 2026-02-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_populate_payment_tariffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttariff',
            name='fee_percent',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Porcentagem de acréscimo (ex: 2.5 para 2.5%)', max_digits=4),
        ),
    ]
