# Generated by Django 6.0.2 on 2026-02-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_paymenttariff_fee_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchitectCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percent', models.DecimalField(decimal_places=1, default=10.0, help_text='Porcentagem de comissão do arquiteto (ex: 10.0 para 10%)', max_digits=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comissão de Arquiteto',
                'verbose_name_plural': 'Comissão de Arquiteto',
            },
        ),
    ]
