# Generated by Django 6.0.2 on 2026-02-19 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_architectcommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMarginConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_margin', models.DecimalField(decimal_places=1, default=16.0, help_text='Margem total (%) dividida entre desconto, taxa do cartão e comissão', max_digits=5)),
                ('min_commission', models.DecimalField(decimal_places=1, default=1.0, help_text='Comissão mínima do vendedor (%)', max_digits=5)),
                ('max_commission', models.DecimalField(decimal_places=1, default=5.0, help_text='Comissão máxima do vendedor (%) — quando desconto = 0', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Margem e Comissão de Vendedor',
                'verbose_name_plural': 'Margem e Comissão de Vendedor',
            },
        ),
    ]
