# Generated by Django 6.0.2 on 2026-03-03 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sales_margin_config'),
        ('sales', '0007_remove_quoteitemimage_expires_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('PHONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('IN_PERSON', 'Presencial'), ('OTHER', 'Outro')], default='OTHER', max_length=12)),
                ('summary', models.TextField()),
                ('next_steps', models.TextField(blank=True, help_text='Próximos passos sugeridos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.customer')),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='sales.quote')),
            ],
            options={
                'verbose_name_plural': 'Communication histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('source', models.CharField(choices=[('PHONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Site'), ('REFERRAL', 'Indicação'), ('WALK_IN', 'Visita à loja'), ('INSTAGRAM', 'Instagram'), ('OTHER', 'Outro')], default='OTHER', max_length=12)),
                ('stage', models.CharField(choices=[('NEW', 'Novo'), ('CONTACTED', 'Contato Feito'), ('QUOTE_SENT', 'Orçamento Enviado'), ('NEGOTIATION', 'Em Negociação'), ('WON', 'Ganho'), ('LOST', 'Perdido')], default='NEW', max_length=12)),
                ('products_of_interest', models.TextField(blank=True, help_text='Produtos de interesse')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, help_text='Faixa de orçamento estimado', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, help_text='Cliente vinculado (após conversão)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='core.customer')),
                ('quote', models.ForeignKey(blank=True, help_text='Orçamento vinculado (se houver)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='sales.quote')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('PHONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('IN_PERSON', 'Presencial'), ('OTHER', 'Outro')], default='OTHER', max_length=12)),
                ('summary', models.TextField(help_text='Resumo da interação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='core.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('DELIVERY_NEAR', 'Entrega próxima'), ('QUOTE_NO_RESPONSE', 'Orçamento sem resposta'), ('GOAL_NEAR', 'Meta próxima de ser atingida'), ('DISCOUNT_AUTH', 'Desconto autorizado'), ('NEW_LEAD', 'Novo lead atribuído'), ('ORDER_CONFIRMED', 'Pedido confirmado'), ('GENERAL', 'Geral')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, help_text='Link para a ação relacionada', max_length=500)),
                ('read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuoteTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('default_unit_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.quotetemplate')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SalesGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COLLECTIVE', 'Coletivo')], default='INDIVIDUAL', max_length=12)),
                ('period', models.CharField(choices=[('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=12)),
                ('period_start', models.DateField(help_text='Início do período')),
                ('period_end', models.DateField(help_text='Fim do período')),
                ('target_value', models.DecimalField(decimal_places=2, help_text='Meta em R$', max_digits=12)),
                ('target_quantity', models.PositiveIntegerField(default=0, help_text='Meta em quantidade de vendas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(blank=True, help_text='Vendedor (para metas individuais)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE_QUOTE', 'Criar orçamento'), ('EDIT_QUOTE', 'Editar orçamento'), ('APPROVE_DISCOUNT', 'Aprovar desconto'), ('CONVERT_ORDER', 'Converter em pedido'), ('EDIT_VALUES', 'Editar valores'), ('CREATE_LEAD', 'Criar lead'), ('CONVERT_LEAD', 'Converter lead'), ('SAVE_CONDITIONS', 'Salvar condições'), ('LOGIN', 'Login'), ('OTHER', 'Outro')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, help_text='Ex: Quote, Order, Lead', max_length=50)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='core_auditl_created_1a76fa_idx'), models.Index(fields=['user', '-created_at'], name='core_auditl_user_id_969660_idx'), models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['stage'], name='core_lead_stage_01080b_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['seller'], name='core_lead_seller__7d58ed_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'read', '-created_at'], name='core_notifi_recipie_f3d353_idx'),
        ),
    ]
