# Generated by Django 6.0.2 on 2026-03-15 20:30

import core.validador
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_communicationhistory_lead_leadinteraction_and_more'),
        ('sales', '0008_proposalconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Log de Auditoria', 'verbose_name_plural': 'Logs de Auditoria'},
        ),
        migrations.AlterModelOptions(
            name='communicationhistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Histórico de Comunicação', 'verbose_name_plural': 'Histórico de Comunicações'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Lead', 'verbose_name_plural': 'Leads'},
        ),
        migrations.AlterModelOptions(
            name='leadinteraction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Interação com Lead', 'verbose_name_plural': 'Interações com Leads'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AlterModelOptions(
            name='quotetemplate',
            options={'ordering': ['name'], 'verbose_name': 'Modelo de Orçamento', 'verbose_name_plural': 'Modelos de Orçamento'},
        ),
        migrations.AlterModelOptions(
            name='quotetemplateitem',
            options={'ordering': ['id'], 'verbose_name': 'Item do Modelo', 'verbose_name_plural': 'Itens do Modelo'},
        ),
        migrations.AlterModelOptions(
            name='salesgoal',
            options={'ordering': ['-period_start'], 'verbose_name': 'Meta de Vendas', 'verbose_name_plural': 'Metas de Vendas'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Fornecedor', 'verbose_name_plural': 'Fornecedores'},
        ),
        migrations.AlterModelOptions(
            name='supplierpaymentoption',
            options={'ordering': ['-is_default', 'days_to_pay'], 'verbose_name': 'Forma de Pagamento do Fornecedor', 'verbose_name_plural': 'Formas de Pagamento do Fornecedor'},
        ),
        migrations.RemoveConstraint(
            model_name='customer',
            name='cpf_or_cnpj_required',
        ),
        migrations.AlterField(
            model_name='architectcommission',
            name='commission_percent',
            field=models.DecimalField(decimal_places=1, default=10.0, help_text='Porcentagem de comissão do arquiteto (ex: 10.0 para 10%)', max_digits=4, verbose_name='Comissão (%)'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_QUOTE', 'Criar orçamento'), ('EDIT_QUOTE', 'Editar orçamento'), ('APPROVE_DISCOUNT', 'Aprovar desconto'), ('CONVERT_ORDER', 'Converter em pedido'), ('EDIT_VALUES', 'Editar valores'), ('CREATE_LEAD', 'Criar lead'), ('CONVERT_LEAD', 'Converter lead'), ('SAVE_CONDITIONS', 'Salvar condições'), ('LOGIN', 'Login'), ('OTHER', 'Outro')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Dados Extras'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID do Objeto'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(blank=True, help_text='Ex: Quote, Order, Lead', max_length=50, verbose_name='Tipo de Objeto'),
        ),
        migrations.AlterField(
            model_name='communicationhistory',
            name='channel',
            field=models.CharField(choices=[('PHONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'E-mail'), ('IN_PERSON', 'Presencial'), ('OTHER', 'Outro')], default='OTHER', max_length=12, verbose_name='Canal'),
        ),
        migrations.AlterField(
            model_name='communicationhistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='communicationhistory',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='core.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='communicationhistory',
            name='next_steps',
            field=models.TextField(blank=True, help_text='Próximos passos sugeridos', verbose_name='Próximos Passos'),
        ),
        migrations.AlterField(
            model_name='communicationhistory',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to='sales.quote', verbose_name='Orçamento'),
        ),
        migrations.AlterField(
            model_name='communicationhistory',
            name='summary',
            field=models.TextField(verbose_name='Resumo'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ válido (com ou sem máscara)', max_length=18, validators=[core.validador.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF válido (com ou sem máscara)', max_length=14, validators=[core.validador.validate_cpf], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('PHONE', 'Telefone'), ('WHATSAPP', 'WhatsApp'), ('WEBSITE', 'Site'), ('REFERRAL', 'Indicação'), ('WALK_IN', 'Visita à loja'), ('INSTAGRAM', 'Instagram'), ('OTHER', 'Outro')], default='OTHER', max_length=12, verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('NEW', 'Novo'), ('CONTACTED', 'Contato Feito'), ('QUOTE_SENT', 'Orçamento Enviado'), ('NEGOTIATION', 'Em Negociação'), ('WON', 'Ganho'), ('LOST', 'Perdido')], default='NEW', max_length=12, verbose_name='Estágio'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(blank=True, verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DELIVERY_NEAR', 'Entrega próxima'), ('QUOTE_NO_RESPONSE', 'Orçamento sem resposta'), ('GOAL_NEAR', 'Meta próxima de ser atingida'), ('DISCOUNT_AUTH', 'Desconto autorizado'), ('NEW_LEAD', 'Novo lead atribuído'), ('ORDER_CONFIRMED', 'Pedido confirmado'), ('GENERAL', 'Geral')], default='GENERAL', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Lida'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Lida em'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, help_text='Link para a ação relacionada', max_length=500, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='paymenttariff',
            name='fee_percent',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Porcentagem de acréscimo (ex: 2.5 para 2.5%)', max_digits=4, verbose_name='Taxa (%)'),
        ),
        migrations.AlterField(
            model_name='paymenttariff',
            name='installments',
            field=models.PositiveIntegerField(help_text='Número de parcelas (1 = à vista)', verbose_name='Parcelas'),
        ),
        migrations.AlterField(
            model_name='paymenttariff',
            name='payment_type',
            field=models.CharField(choices=[('CASH', 'Dinheiro'), ('PIX', 'PIX'), ('CREDIT_CARD', 'Cartão de Crédito'), ('CHEQUE', 'Cheque'), ('BOLETO', 'Boleto')], help_text='Tipo do método de pagamento', max_length=20, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='salesgoal',
            name='goal_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COLLECTIVE', 'Coletivo')], default='INDIVIDUAL', max_length=12, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='salesgoal',
            name='period',
            field=models.CharField(choices=[('MONTHLY', 'Mensal'), ('QUARTERLY', 'Trimestral'), ('YEARLY', 'Anual')], default='MONTHLY', max_length=12, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='salesgoal',
            name='period_end',
            field=models.DateField(help_text='Fim do período', verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='salesgoal',
            name='period_start',
            field=models.DateField(help_text='Início do período', verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='salesgoal',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Vendedor (para metas individuais)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_goals', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='salesgoal',
            name='target_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Meta em quantidade de vendas', verbose_name='Meta (Qtd)'),
        ),
        migrations.AlterField(
            model_name='salesgoal',
            name='target_value',
            field=models.DecimalField(decimal_places=2, help_text='Meta em R$', max_digits=12, verbose_name='Meta (R$)'),
        ),
        migrations.AlterField(
            model_name='salesmarginconfig',
            name='max_commission',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Comissão máxima do vendedor (%) — quando desconto = 0', max_digits=5, verbose_name='Comissão Máxima (%)'),
        ),
        migrations.AlterField(
            model_name='salesmarginconfig',
            name='min_commission',
            field=models.DecimalField(decimal_places=1, default=1.0, help_text='Comissão mínima do vendedor (%)', max_digits=5, verbose_name='Comissão Mínima (%)'),
        ),
        migrations.AlterField(
            model_name='salesmarginconfig',
            name='total_margin',
            field=models.DecimalField(decimal_places=1, default=16.0, help_text='Margem total (%) dividida entre desconto, taxa do cartão e comissão', max_digits=5, verbose_name='Margem Total (%)'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='address',
            field=models.TextField(blank=True, help_text='Endereço completo', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='cnpj',
            field=models.CharField(blank=True, help_text='CNPJ da transportadora (opcional)', max_length=18, validators=[core.validador.validate_cnpj], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='contact_person',
            field=models.CharField(blank=True, help_text='Pessoa de contato na transportadora', max_length=100, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Transportadora ativa', verbose_name='Ativa'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='name',
            field=models.CharField(help_text='Nome da transportadora', max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='notes',
            field=models.TextField(blank=True, help_text='Observações', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='payment_methods',
            field=models.TextField(blank=True, help_text='Métodos de pagamento disponíveis (um por linha)', verbose_name='Métodos de Pagamento'),
        ),
        migrations.AlterField(
            model_name='shippingcompany',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(help_text='E-mail único do fornecedor (identificador principal)', max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, help_text='Informações adicionais sobre o fornecedor', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_number',
            field=models.CharField(help_text='Número/código do fornecedor', max_length=50, unique=True, verbose_name='Código'),
        ),
    ]
