# Generated by Django 6.0.2 on 2026-03-16 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_cpf_cnpj_required_constraint'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='core_lead_stage_01080b_idx',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='core_lead_seller__7d58ed_idx',
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_QUOTE', 'Criar orçamento'), ('EDIT_QUOTE', 'Editar orçamento'), ('APPROVE_DISCOUNT', 'Aprovar desconto'), ('CONVERT_ORDER', 'Converter em pedido'), ('EDIT_VALUES', 'Editar valores'), ('SAVE_CONDITIONS', 'Salvar condições'), ('LOGIN', 'Login'), ('OTHER', 'Outro')], max_length=20, verbose_name='Ação'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='object_type',
            field=models.CharField(blank=True, help_text='Ex: Quote, Order', max_length=50, verbose_name='Tipo de Objeto'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('DELIVERY_NEAR', 'Entrega próxima'), ('QUOTE_NO_RESPONSE', 'Orçamento sem resposta'), ('GOAL_NEAR', 'Meta próxima de ser atingida'), ('DISCOUNT_AUTH', 'Desconto autorizado'), ('ORDER_CONFIRMED', 'Pedido confirmado'), ('GENERAL', 'Geral')], default='GENERAL', max_length=20, verbose_name='Tipo'),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='seller',
        ),
        migrations.DeleteModel(
            name='LeadInteraction',
        ),
        migrations.DeleteModel(
            name='Lead',
        ),
    ]
