# Generated by Django 6.0.3 on 2026-03-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_lead_core_lead_stage_01080b_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierPaymentOption',
        ),
    ]
