# Generated by Django 6.0.3 on 2026-03-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_supplierpaymentoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_number',
            field=models.PositiveIntegerField(editable=False, unique=True, verbose_name='Código'),
        ),
    ]
