# Generated by Django 6.0.3 on 2026-03-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_supplier_auto_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttariff',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentagem de acréscimo (ex: 5.32 para 5.32%)', max_digits=5, verbose_name='Taxa (%)'),
        ),
        migrations.AlterField(
            model_name='salesmarginconfig',
            name='total_margin',
            field=models.DecimalField(decimal_places=1, default=10.0, help_text='Margem da empresa (%)', max_digits=5, verbose_name='Margem Total (%)'),
        ),
    ]
