# Generated by Django 6.0.2 on 2026-03-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_salesmarginconfig_margin_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Architect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Nome Completo')),
                ('pix', models.CharField(max_length=120, verbose_name='Chave PIX')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Cadastrado em')),
            ],
            options={
                'verbose_name': 'Arquiteto',
                'verbose_name_plural': 'Arquitetos',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='salesmarginconfig',
            name='total_margin',
            field=models.DecimalField(decimal_places=1, default=12.0, help_text='Margem ideal da empresa (%). Abaixo disso a comissão sobe, acima desce.', max_digits=5, verbose_name='Margem Ideal (%)'),
        ),
    ]
