# Generated by Django 6.0.3 on 2026-03-28 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_architect_alter_salesmarginconfig_total_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmarginconfig',
            name='margin_limit',
            field=models.DecimalField(decimal_places=1, default=10.0, help_text='Custo total máximo permitido (%). Acima desse valor o orçamento é bloqueado.', max_digits=5, verbose_name='Limite de Margem (%)'),
        ),
    ]
