# Generated by Django 6.0.3 on 2026-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_change_margin_limit_default_to_10'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmarginconfig',
            name='margin_limit',
        ),
        migrations.AlterField(
            model_name='salesmarginconfig',
            name='min_commission',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Comissão mínima do vendedor (%)', max_digits=5, verbose_name='Comissão Mínima (%)'),
        ),
        migrations.AlterField(
            model_name='salesmarginconfig',
            name='total_margin',
            field=models.DecimalField(decimal_places=1, default=10.0, help_text='Margem da empresa (%). Custos acima desse valor bloqueiam o orçamento.', max_digits=5, verbose_name='Margem (%)'),
        ),
    ]
