# Generated by Django 6.0.2 on 2026-04-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_debit_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architect',
            name='pix',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Chave PIX'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE_QUOTE', 'Criar orçamento'), ('EDIT_QUOTE', 'Editar orçamento'), ('DELETE_QUOTE', 'Excluir orçamento'), ('APPROVE_DISCOUNT', 'Aprovar desconto'), ('CONVERT_ORDER', 'Converter em pedido'), ('EDIT_VALUES', 'Editar valores'), ('SAVE_CONDITIONS', 'Salvar condições'), ('LOGIN', 'Login'), ('OTHER', 'Outro')], max_length=20, verbose_name='Ação'),
        ),
    ]
