# Generated by Django 6.0.2 on 2026-02-25 00:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0007_sales_margin_config'),
        ('sales', '0006_alter_quoteitem_architect_percent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título do evento', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada')),
                ('event_type', models.CharField(choices=[('DELIVERY', 'Entrega'), ('QUOTE_FOLLOWUP', 'Follow-up de Orçamento'), ('CUSTOM', 'Personalizado')], default='CUSTOM', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('DONE', 'Concluído'), ('OVERDUE', 'Atrasado'), ('CANCELED', 'Cancelado')], default='PENDING', max_length=20)),
                ('event_date', models.DateField(help_text='Data do evento')),
                ('event_time', models.TimeField(blank=True, help_text='Horário (opcional)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(help_text='Vendedor responsável', on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, help_text='Cliente vinculado (se aplicável)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='core.customer')),
                ('order', models.ForeignKey(blank=True, help_text='Pedido vinculado (se aplicável)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='sales.order')),
                ('quote', models.ForeignKey(blank=True, help_text='Orçamento vinculado (se aplicável)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='sales.quote')),
            ],
            options={
                'verbose_name': 'Evento do Calendário',
                'verbose_name_plural': 'Eventos do Calendário',
                'ordering': ['event_date', 'event_time'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remind_date', models.DateField(help_text='Data para enviar o lembrete')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('SENT', 'Enviado'), ('DISMISSED', 'Dispensado')], default='SCHEDULED', max_length=20)),
                ('message', models.CharField(blank=True, help_text='Mensagem personalizada do lembrete', max_length=300)),
                ('read', models.BooleanField(default=False, help_text='Se o usuário já leu o lembrete')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='calendar_app.calendarevent')),
            ],
            options={
                'verbose_name': 'Lembrete',
                'verbose_name_plural': 'Lembretes',
                'ordering': ['remind_date'],
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_date'], name='calendar_ap_event_d_611266_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type'], name='calendar_ap_event_t_317962_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['status'], name='calendar_ap_status_e36391_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['assigned_to'], name='calendar_ap_assigne_f8d1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['remind_date'], name='calendar_ap_remind__0f11fb_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['status'], name='calendar_ap_status_00fe3f_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['read'], name='calendar_ap_read_43771d_idx'),
        ),
    ]
