# Generated by Django 6.0.2 on 2026-02-25 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_eventattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da etiqueta', max_length=60)),
                ('color', models.CharField(choices=[('#61bd4f', 'Verde'), ('#f2d600', 'Amarelo'), ('#ff9f1a', 'Laranja'), ('#eb5a46', 'Vermelho'), ('#c377e0', 'Roxo'), ('#0079bf', 'Azul'), ('#00c2e0', 'Celeste'), ('#51e898', 'Lima'), ('#ff78cb', 'Rosa'), ('#344563', 'Escuro')], default='#61bd4f', help_text='Cor da etiqueta', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etiqueta',
                'verbose_name_plural': 'Etiquetas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Etiquetas do evento', related_name='events', to='calendar_app.eventtag'),
        ),
    ]
