# Generated by Django 6.0.2 on 2026-03-22 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_eventtag_calendarevent_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('DELIVERY', 'Entrega'), ('QUOTE_FOLLOWUP', 'Follow-up de Orçamento'), ('ARCHITECT_PAYMENT', 'Pagamento Arquiteto'), ('CUSTOM', 'Personalizado')], default='CUSTOM', max_length=20),
        ),
    ]
